version: '3'

networks:
  lan_network:
    driver: bridge

services:
  backup:
    hostname : fr-backup
    build: backup
    volumes:
      - /var/log/mysql-backup:/root/mysql-backup
  apache:
    hostname : fr-apache
    # Build a partir du Dockerfile du dossier apache
    build: apache
    volumes:
      - /var/log/apache-log:/var/log/apache2
    ports:
     - 80:80
  db:
    hostname: fr-mysql
    image: mysql:5.7
    restart: always
    environment:
      # Crétion d'une base de donnée filerouge_db
      MYSQL_DATABASE: 'filrouge_db'
      # Création d'un utilisateur standard
      MYSQL_USER: 'filrouge_user'
      # Mot de passe de l'utilisateur standard
      MYSQL_PASSWORD: 'filrouge_password'
      # Personnalisation du mot de passe root
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      # Exposition du port
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  icinga:
    hostname: fr-icinga
    image: jordan/icinga2
    # volumes:
    #   - ./icinga/hosts.conf:/etc/icinga2/conf.d/hosts.conf
    ports:
    - 8080:80
    
# Déclaration des différents volumes
volumes:
  db:
